---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: application
  labels:
    app.kubernetes.io/instance: librespeed
    app.kubernetes.io/name: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: librespeed
      app.kubernetes.io/name: librespeed
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: librespeed
        app.kubernetes.io/name: librespeed
    spec:
      initContainers:
        - name: mysql-migration
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: librespeed-env
            - secretRef:
                name: librespeed-secret
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for MySQL to be ready..."
              until mysql -h${DB_HOSTNAME} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD} -e "SELECT 1" > /dev/null 2>&1; do
                echo "Waiting for MySQL connection..."
                sleep 2
              done

              echo "Checking if speedtest_users table exists..."
              TABLE_EXISTS=$(mysql -h${DB_HOSTNAME} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD} -D${DB_NAME} -e "SHOW TABLES LIKE 'speedtest_users';" | grep -c speedtest_users || true)

              if [ "$TABLE_EXISTS" -eq "0" ]; then
                echo "Creating speedtest_users table..."
                mysql -h${DB_HOSTNAME} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD} -D${DB_NAME} -e "
                CREATE TABLE speedtest_users (
                  id int(11) NOT NULL AUTO_INCREMENT,
                  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  ip text NOT NULL,
                  ispinfo text,
                  extra text,
                  ua text NOT NULL,
                  lang text NOT NULL,
                  dl text,
                  ul text,
                  ping text,
                  jitter text,
                  log longtext,
                  PRIMARY KEY (id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
                echo "Table speedtest_users created successfully."
              else
                echo "Table speedtest_users already exists, skipping migration."
              fi
      containers:
        - name: librespeed
          image: ghcr.io/librespeed/speedtest:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: librespeed-env
            - secretRef:
                name: librespeed-secret
          volumeMounts:
            - name: servers-config
              mountPath: /servers.json
              subPath: servers.json
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: servers-config
          configMap:
            name: librespeed-servers
