---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.250.106-192.168.250.109
  autoAssign: true
  avoidBuggyIPs: false
