apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
  labels:
    app: db
type: Opaque
data:
  mysql-root-password: ENC[AES256_GCM,data:ykl+WI7KcZLo5DUP,iv:XdBqFrf4e5SuS6aHy6aPCJ+aOLA9oXjZzqcoTSduFxc=,tag:k0HIfNb4FDkzVTYV00y+dQ==,type:str]
  mysql-password: ENC[AES256_GCM,data:G922t6sPQqNQbak/,iv:daZVei4F0PXRcKet0+4OmMr+3urZ/rTzeQm/+c6gcas=,tag:vdTd6kidnpnu7DP6IMeFdA==,type:str]
sops:
  lastmodified: "2025-09-04T19:47:02Z"
  mac: ENC[AES256_GCM,data:87XuwUcJ8gKN8Au7gQxe6R9IP03uvS2iVwMfObgPDJylMmpDAi8l+60Z1IeXvwLhR6vqLAe1OnHrELhnBz5coh0WYJdHnsc7EaiQ8gYkzY3nP4p7fXLDZ3RFID+lfXfBoixldo6JiDxb2WQEPRXW/fknMPEKejbu+ib1ugNqFD4=,iv:Y+HFxZLxTEIlKsQKvC71Wb3z6UsqFwvkbUMkXFtLm2A=,tag:3rls1oPTh3YlYv/jjNr3wA==,type:str]
  pgp:
    - created_at: "2025-09-04T19:47:02Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA+/5db3erMwDARAAihHfMrceDzL95g5tHrBKFqrNyzyZ4npK/3jzrk/gSjjO
        sWooxVSJVLoNAaG8O45YceOI2tKKkSCu8OezgQuzXLb1SBpcbzOTPtjJ68U/jPVC
        CVIJDrzTIUmJONFWyBlsSgsnBRorgQVmcqSHS2rzbTjbjVl7RSJWlwKKpgURlz05
        UrB7ipiZxe2t8GWc2s78JPR3VxpS/6vVCHMqc3jZJgXZzBoOCIgi/gvN78yGP7iN
        5GvyjUnVrp3jQKe5zG748Aq++eqNbYHXT5cMS60Yy90vCD8g/hNx7e0WAeFwUAcC
        sOtKDmV9ISWG7EwWo8G7NrPTzAgmp2K6zngtEDVrEpgHFeCMsChfJLQsY7WDJeyV
        RjINrCh4Kpn2QM9fTDM3SW9Ra2Lz8u/IQJuKZwhNLCbQ0gR1r/xpnxLkIdgN4OWG
        G2EaLE2WgMmNEHHwG+gQQP4lAN3LyrjnhltlEG3vlZBQwpMjxnYIo+Zr7ASeAbjU
        tbUlI5zJq/kfpQCDS5l4AqXclvN3w3Dia4qKVz5c+hrR0RdIVb2B2W8Gk9BxWZij
        kZ1NOgrhS6V/Yms5SlPF/qrkIu8nbmOmMq9xQP1pxiy1hnIwXE6Std9k2oa0ysJB
        ez1LYAFbgf/jHus7qXacWoe6gI5esVNmOxEodrzoiK87SPmyW5ME7fNVkQ8maejS
        XgG5D1T3c0kk55n3GPi2PFfdjE8oDt8gU58B3bsPA2/1wdT6xJBgPG/uZKpKtOtE
        fYo7cTTn2LBwarTY8LbiyybvyzKXaJ6OG0Qe88OfesNMkFeKEDeK2zJLi9OxUaE=
        =RZsz
        -----END PGP MESSAGE-----
      fp: EFA3A48930E2DF650369061E62D3D8BB58AD7947
  encrypted_regex: ^(token_id|token_secret|mysql-root-password|mysql-password)$
  version: 3.10.2
